apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
#  schedule: "*/1 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: dev
    - name: statusholder_url
      value: https://statusholder.dev-fss-pub.nais.io
    - name: portalserver_path
      value: https://status-api.intern.dev.nav.no/rest

  azure:
    application:
      enabled: true

  accessPolicy:
    inbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
        - application: statusholder
          namespace: navdig
          cluster: dev-fss
  webproxy: true

