apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  #  schedule: "*/1 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
    - name: statusholder_url
      value: https://statusholder.prod-fss-pub.nais.io
    - name: portalserver_path
      value: https://status-api.nav.no/rest

  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp
        - application: statusholder
          namespace: navdig
          cluster: prod-fss
