apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  schedule: "*/1 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: dev
  azure:
    application:
      enabled: true

  accessPolicy:
    inbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
        - application: statusholder
          namespace: navdig
          cluster: dev-fss
  webproxy: true

