apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  schedule: "*/3 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
    - name: statusholder_url
      value: http://statusholder
    - name: portalserver_path
      value: http://portalserver.navdig.svc.cluster.local

  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp
        - application: statusholder
          namespace: navdig
          cluster: prod-fss

