apiVersion: nais.io/v1alpha1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: dev
  azure:
    application:
      enabled: true

  accessPolicy:
    inbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp

