apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: onpremstatuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  schedule: "*/3 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
    - name: statusholder_url
      value: http://statusholder
    - name: portalserver_path
      value: https://status-api.nav.no/rest

  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp
  webproxy: true
